$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$tmp=Join-Path $env:TEMP "storyboard-security-$([guid]::NewGuid())"
New-Item -ItemType Directory -Force "$tmp\release-artifacts","$tmp\src-tauri"|Out-Null
function Expect-Reject([string]$Name,[scriptblock]$Action){try{&$Action;throw "TEST_UNEXPECTED_SUCCESS:$Name"}catch{if($_.Exception.Message.StartsWith('TEST_UNEXPECTED_SUCCESS:')){throw};Write-Output "${Name}: reject"}}
try {
 Copy-Item VERSION "$tmp\VERSION"; Copy-Item package.json "$tmp\package.json"; Copy-Item src-tauri\tauri.conf.json "$tmp\src-tauri\tauri.conf.json"; Copy-Item scripts\release-preflight.ps1 "$tmp\preflight.ps1"
 $rsa=[Security.Cryptography.RSA]::Create(2048);$priv="$tmp\p.pem";$pub="$tmp\u.pem";$rsa.ExportRSAPrivateKeyPem()|Set-Content $priv -NoNewline;$rsa.ExportRSAPublicKeyPem()|Set-Content $pub -NoNewline
 $cfg=Get-Content "$tmp\src-tauri\tauri.conf.json" -Raw|ConvertFrom-Json;$cfg.plugins.updater.pubkey=Get-Content $pub -Raw;$cfg|ConvertTo-Json -Depth 20|Set-Content "$tmp\src-tauri\tauri.conf.json"
 $a="$tmp\release-artifacts\a.bin";Set-Content $a fixture;$h=(Get-FileHash $a -Algorithm SHA256).Hash.ToUpper();$s=[Convert]::ToBase64String($rsa.SignData([Text.Encoding]::UTF8.GetBytes($h),[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1));$m=@{version='99.0.0';artifactPath='release-artifacts/a.bin';sha256=$h;signature=$s;allowDowngrade=$false}|ConvertTo-Json;Set-Content "$tmp\release-artifacts\m.json" $m
 & "$tmp\preflight.ps1" -Mode release -WorkspaceRoot $tmp -UpdateEndpoint https://updates.storyboard-editor.example -SigningKeyPath $priv -PublicKeyPath $pub -PinnedPublicKeyPath $pub -MetadataPath "$tmp\release-artifacts\m.json"|Out-Null;Write-Output 'valid: pass'
 Expect-Reject 'tampered-artifact' {Add-Content $a tamper;& "$tmp\preflight.ps1" -Mode release -WorkspaceRoot $tmp -UpdateEndpoint https://updates.storyboard-editor.example -SigningKeyPath $priv -PublicKeyPath $pub -PinnedPublicKeyPath $pub -MetadataPath "$tmp\release-artifacts\m.json"|Out-Null}
 Expect-Reject 'http' {& "$tmp\preflight.ps1" -Mode release -WorkspaceRoot $tmp -UpdateEndpoint http://updates.storyboard-editor.example -SigningKeyPath $priv -PublicKeyPath $pub -PinnedPublicKeyPath $pub -MetadataPath "$tmp\release-artifacts\m.json"|Out-Null}
 $base=Get-Content "$tmp\release-artifacts\m.json"|ConvertFrom-Json
 foreach($case in @('hash','path','version','unsigned','downgrade','malformed','traversal','absolute','allowDowngrade')) { $x=$base.PSObject.Copy();switch($case){hash{$x.sha256='0'*64};path{$x.artifactPath='../x'};version{$x.version='0.1.0'};unsigned{$x.signature=''};downgrade{$x.allowDowngrade=$true};malformed{$x.signature='%%%'};traversal{$x.artifactPath='../x'};absolute{$x.artifactPath='C:\x'};allowDowngrade{$x.allowDowngrade=$true}};$x|ConvertTo-Json|Set-Content "$tmp\release-artifacts\m.json";Expect-Reject "tamper-$case" {& "$tmp\preflight.ps1" -Mode release -WorkspaceRoot $tmp -UpdateEndpoint https://updates.storyboard-editor.example -SigningKeyPath $priv -PublicKeyPath $pub -PinnedPublicKeyPath $pub -MetadataPath "$tmp\release-artifacts\m.json"|Out-Null};$base|ConvertTo-Json|Set-Content "$tmp\release-artifacts\m.json" }
 $wrong=[Security.Cryptography.RSA]::Create(2048);$wp="$tmp\wrong.pem";$wrong.ExportRSAPublicKeyPem()|Set-Content $wp -NoNewline;Expect-Reject 'wrong-key' {& "$tmp\preflight.ps1" -Mode release -WorkspaceRoot $tmp -UpdateEndpoint https://updates.storyboard-editor.example -SigningKeyPath $priv -PublicKeyPath $wp -PinnedPublicKeyPath $pub -MetadataPath "$tmp\release-artifacts\m.json"|Out-Null}
 $c=Get-Content "$tmp\src-tauri\tauri.conf.json" -Raw|ConvertFrom-Json;$c.plugins.updater.pubkey='__INJECT_PINNED_ED25519_PUBLIC_KEY__';$c|ConvertTo-Json -Depth 20|Set-Content "$tmp\src-tauri\tauri.conf.json";Expect-Reject 'placeholder' {& "$tmp\preflight.ps1" -Mode release -WorkspaceRoot $tmp -UpdateEndpoint https://updates.storyboard-editor.example -SigningKeyPath $priv -PublicKeyPath $pub -MetadataPath "$tmp\release-artifacts\m.json"|Out-Null}
 $vr=Join-Path $tmp 'versions'; New-Item -ItemType Directory -Force "$vr\src-tauri"|Out-Null
 Set-Content "$vr\VERSION" 1.1.0; Set-Content "$vr\package.json" '{"version":"1.1.0"}'; Set-Content "$vr\Cargo.toml" -Value @('[workspace.package]','version = "1.1.0"'); Set-Content "$vr\src-tauri\tauri.conf.json" '{"version":"1.1.0"}'
 & "$root\scripts\release-version-check.ps1" -Root $vr -TagVersion 1.1.0 -PreviousVersion 1.0.0|Out-Null; Write-Output 'version-valid: pass'
 foreach($f in @('VERSION','package.json','Cargo.toml','src-tauri/tauri.conf.json')) { $old=Get-Content "$vr\$f" -Raw; if($f -eq 'Cargo.toml'){Set-Content "$vr\$f" -Value @('[workspace.package]','version = "0.9.0"')}elseif($f -eq 'package.json'){Set-Content "$vr\$f" '{"version":"0.9.0"}'}elseif($f -eq 'src-tauri/tauri.conf.json'){Set-Content "$vr\$f" '{"version":"0.9.0"}'}else{Set-Content "$vr\$f" 0.9.0}; Expect-Reject "version-mismatch-$f" {& "$root\scripts\release-version-check.ps1" -Root $vr -TagVersion 1.1.0 -PreviousVersion 1.0.0|Out-Null}; Set-Content "$vr\$f" $old }
 $sr=Join-Path $tmp 'source';New-Item -ItemType Directory -Force "$sr\src"|Out-Null;Set-Content "$sr\src\safe.txt" safe;& "$root\scripts\package-source.ps1" -SourceRoot $sr -OutputPath "$tmp\safe.zip"|Out-Null;Write-Output 'source-safe: pass';$privateKeyFixture=(('-----BEGIN ','PRIVATE KEY-----') -join '');foreach($v in @('bad.pem','bad.txt')){Set-Content "$sr\src\$v" ($(if($v -eq 'bad.pem'){'x'}else{$privateKeyFixture}));Expect-Reject "source-$v" {& "$root\scripts\package-source.ps1" -SourceRoot $sr -OutputPath "$tmp\bad.zip"|Out-Null};Remove-Item "$sr\src\$v"};$sourceFixtures=@((('password',' = secret') -join ''),(('token',' = ','ghp_','abcdefghijklmnopqrstuvwxyz123456') -join ''));foreach($s in $sourceFixtures){Set-Content "$sr\src\bad.txt" $s;Expect-Reject 'source-content' {& "$root\scripts\package-source.ps1" -SourceRoot $sr -OutputPath "$tmp\bad.zip"|Out-Null};Remove-Item "$sr\src\bad.txt"}
 $official='dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IEJBMENDOEMwM0ZEN0Q0RkUKUldUKzFOYy93TWdNdWtUSTFnaWZ2bFlWVzRJSnhPcE96SldHWkczRHM4NEtOOGlvNmRjT2VBNlAK';& "$root\scripts\validate-tauri-updater-key.ps1" -Key $official|Out-Null;Write-Output 'tauri-key-official: pass';foreach($k in @('-----BEGIN PUBLIC KEY-----',$official.Substring(0,40),([Convert]::ToBase64String((0..31|%{[byte]$_}))),'%%%')){Expect-Reject 'tauri-key-invalid' {& "$root\scripts\validate-tauri-updater-key.ps1" -Key $k|Out-Null}}
 $outerText=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($official));$keyLines=$outerText -split "`n";$commentPrefix=$keyLines[0].Substring(0,$keyLines[0].Length-16);$commentId=$keyLines[0].Substring($keyLines[0].Length-16);$changedFirst=if($commentId[0] -eq '0'){'1'}else{'0'};$keyLines[0]=$commentPrefix+$changedFirst+$commentId.Substring(1);$idMismatch=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(($keyLines -join "`n")));Expect-Reject 'tauri-key-id-mismatch' { & "$root\scripts\validate-tauri-updater-key.ps1" -Key $idMismatch | Out-Null }
Expect-Reject 'tauri-key-valid-length-random' { & "$root\scripts\validate-tauri-updater-key.ps1" -Key ([Convert]::ToBase64String((0..63|%{[byte]$_}))) | Out-Null }
$extra=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("$outerText`nextra"));Expect-Reject 'tauri-key-extra-line' { & "$root\scripts\validate-tauri-updater-key.ps1" -Key $extra | Out-Null }
$ib=[Convert]::FromBase64String($keyLines[1]);$ib[0]=0x46;$wm=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("$($keyLines[0])`n$([Convert]::ToBase64String($ib))`n"));Expect-Reject 'tauri-key-wrong-marker' { & "$root\scripts\validate-tauri-updater-key.ps1" -Key $wm | Out-Null }
} finally {Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue}
