use std::path::{Path, PathBuf};
use storyboard_core::{
    create_project, is_safe_relative_path, load_project, save_project, validate_project,
    ShotStatus, StoryboardProject,
};
use tauri::Manager;

fn workspace_root(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|path| path.join("workspace"))
        .map_err(|error| error.to_string())
}

#[tauri::command]
fn new_project(root: String, title: String) -> Result<String, String> {
    create_project(root, &title)
        .map(|path| path.to_string_lossy().into_owned())
        .map_err(|error| error.to_string())
}

#[tauri::command]
fn open_project(project_root: String) -> Result<StoryboardProject, String> {
    load_project(project_root).map_err(|error| error.to_string())
}

#[tauri::command]
fn write_project(project_root: String, project: StoryboardProject) -> Result<(), String> {
    save_project(project_root, &project).map_err(|error| error.to_string())
}

#[tauri::command]
fn load_workspace(app: tauri::AppHandle) -> Result<Option<StoryboardProject>, String> {
    let root = workspace_root(&app)?;
    if !root.join(storyboard_core::PROJECT_FILE).exists() {
        return Ok(None);
    }
    load_project(root)
        .map(Some)
        .map_err(|error| error.to_string())
}

#[tauri::command]
fn save_workspace(app: tauri::AppHandle, project: StoryboardProject) -> Result<String, String> {
    let root = workspace_root(&app)?;
    save_project(&root, &project).map_err(|error| error.to_string())?;
    Ok(root
        .join(storyboard_core::PROJECT_FILE)
        .to_string_lossy()
        .into_owned())
}

#[tauri::command]
fn resolve_workspace_media(app: tauri::AppHandle, relative_path: String) -> Result<String, String> {
    if !is_safe_relative_path(&relative_path) {
        return Err("媒體路徑必須是工作區內相對路徑".into());
    }
    Ok(workspace_root(&app)?
        .join(relative_path)
        .to_string_lossy()
        .into_owned())
}

fn concat_escape(path: &str) -> String {
    path.replace('\\', "/").replace('\'', "'\\''")
}

#[tauri::command]
fn export_artifacts(
    app: tauri::AppHandle,
    project: StoryboardProject,
    confirmed: bool,
) -> Result<String, String> {
    if !confirmed {
        return Err("使用者尚未確認覆寫匯出檔案".into());
    }
    let root = workspace_root(&app)?;
    save_project(&root, &project).map_err(|error| error.to_string())?;
    let export_dir = root.join("04_exports");
    std::fs::create_dir_all(&export_dir).map_err(|error| error.to_string())?;

    let json = serde_json::to_string_pretty(&project).map_err(|error| error.to_string())? + "\n";
    std::fs::write(export_dir.join("storyboard.json"), json).map_err(|error| error.to_string())?;

    let mut concat = String::from("# FFmpeg concat demuxer list generated by Storyboard Editor\n");
    for shot in project.shots.iter().filter(|shot| {
        shot.enabled && shot.status != ShotStatus::Archived && !shot.visual.path.trim().is_empty()
    }) {
        let media = root.join(&shot.visual.path);
        concat.push_str(&format!(
            "file '{}'\n",
            concat_escape(&media.to_string_lossy())
        ));
        concat.push_str(&format!(
            "duration {:.3}\n",
            shot.duration_ms as f64 / 1000.0
        ));
    }
    std::fs::write(export_dir.join("ffmpeg-concat.txt"), concat)
        .map_err(|error| error.to_string())?;

    let command = "ffmpeg -f concat -safe 0 -i ffmpeg-concat.txt -c:v libx264 -pix_fmt yuv420p -r 30 storyboard-preview.mp4\n";
    std::fs::write(export_dir.join("ffmpeg-command.txt"), command)
        .map_err(|error| error.to_string())?;
    Ok(export_dir.to_string_lossy().into_owned())
}

#[tauri::command]
fn check_project(project: StoryboardProject) -> Vec<String> {
    validate_project(&project)
        .into_iter()
        .map(|issue| format!("{:?} {}: {}", issue.severity, issue.path, issue.message))
        .collect()
}

#[tauri::command]
fn import_asset(
    project_root: String,
    source: String,
    relative_destination: String,
) -> Result<String, String> {
    if !is_safe_relative_path(&relative_destination) {
        return Err("素材目的地必須是專案內相對路徑".into());
    }
    let root = PathBuf::from(project_root);
    let source_path = PathBuf::from(source);
    if !source_path.is_file() {
        return Err("找不到來源素材".into());
    }
    let destination = root.join(Path::new(&relative_destination));
    if destination.exists() {
        return Err(format!(
            "目的地已存在，為避免覆寫而停止: {}",
            destination.display()
        ));
    }
    if let Some(parent) = destination.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::copy(&source_path, &destination).map_err(|e| e.to_string())?;
    Ok(relative_destination)
}

#[tauri::command]
async fn check_for_update(app: tauri::AppHandle) -> Result<Option<String>, String> {
    use tauri_plugin_updater::UpdaterExt;
    let update = app
        .updater()
        .map_err(|e| e.to_string())?
        .check()
        .await
        .map_err(|e| e.to_string())?;
    Ok(update.map(|item| item.version))
}

#[tauri::command]
async fn install_update(app: tauri::AppHandle, confirmed: bool) -> Result<String, String> {
    if !confirmed {
        return Err("使用者尚未確認更新影響".into());
    }
    use tauri_plugin_updater::UpdaterExt;
    let update = app
        .updater()
        .map_err(|e| e.to_string())?
        .check()
        .await
        .map_err(|e| e.to_string())?
        .ok_or("目前沒有可用更新")?;
    let version = update.version.clone();
    update
        .download_and_install(|_, _| {}, || {})
        .await
        .map_err(|e| e.to_string())?;
    Ok(format!("已安裝 {version}，請重新啟動應用程式完成更新"))
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .invoke_handler(tauri::generate_handler![
            new_project,
            open_project,
            write_project,
            load_workspace,
            save_workspace,
            resolve_workspace_media,
            export_artifacts,
            check_project,
            import_asset,
            check_for_update,
            install_update
        ])
        .run(tauri::generate_context!())
        .expect("error while running Storyboard Editor");
}
